import type { Preset } from "./map";

export const PRESETS: Preset[] = [
  {
    id: "desert-canyon", name: "Desert canyon",
    description: "Dry ravines, mesas, an oasis, and a winding trail.",
    width: 36, height: 24, seed: "", scale: 7, mode: "desert-canyon",
    waterWeight: .6, difficultWeight: 1, reliefWeight: 1.3,
    rockRatio: .055, treeRatio: .005, buildingCount: 1,
  },
  {
    id: "ancient-forest", name: "Ancient forest",
    description: "Dense old growth, clearings, rough undergrowth, and streams.",
    width: 36, height: 24, seed: "", scale: 9, mode: "ancient-forest",
    waterWeight: .7, difficultWeight: 1.2, reliefWeight: .4,
    rockRatio: .02, treeRatio: .22, buildingCount: 0,
  },
  {
    id: "frozen-lake", name: "Frozen lake",
    description: "A broad frozen basin, open water, snow, and rocky shores.",
    width: 36, height: 24, seed: "", scale: 9, mode: "frozen-lake",
    waterWeight: 1, difficultWeight: 1.1, reliefWeight: .5,
    rockRatio: .025, treeRatio: .025, buildingCount: 0,
  },
  {
    id: "badlands", name: "Badlands",
    description: "Broken ridges, dry gullies, exposed ground, and narrow routes.",
    width: 36, height: 24, seed: "", scale: 6, mode: "badlands",
    waterWeight: .1, difficultWeight: 1.3, reliefWeight: 1.5,
    rockRatio: .07, treeRatio: 0, buildingCount: 0,
  },
  {
    id: "ruined-battlefield", name: "Ruined battlefield",
    description: "Craters, trenches, wrecked structures, and churned earth.",
    width: 36, height: 24, seed: "", scale: 7, mode: "ruined-battlefield",
    waterWeight: .2, difficultWeight: 1.5, reliefWeight: .9,
    rockRatio: .045, treeRatio: .01, buildingCount: 5,
  },
  {
    id: "farmland", name: "Farmland",
    description: "Fields, lanes, farmsteads, drainage, and open sightlines.",
    width: 36, height: 24, seed: "", scale: 10, mode: "farmland",
    waterWeight: .35, difficultWeight: .8, reliefWeight: .1,
    rockRatio: .005, treeRatio: .035, buildingCount: 3,
  },
  {
    id: "archipelago", name: "Archipelago",
    description: "Separated islands, beaches, shallows, and scattered vegetation.",
    width: 36, height: 24, seed: "", scale: 8, mode: "archipelago",
    waterWeight: 1, difficultWeight: .5, reliefWeight: .4,
    rockRatio: .03, treeRatio: .07, buildingCount: 1,
  },
  {
    id: "mountain-pass", name: "Mountain pass",
    description: "Opposing cliff faces, a traversable pass, and high trails.",
    width: 36, height: 24, seed: "", scale: 6, mode: "mountain-pass",
    waterWeight: .25, difficultWeight: 1, reliefWeight: 1.6,
    rockRatio: .065, treeRatio: .02, buildingCount: 1,
  },
  {
    id: "sewer", name: "Sewer",
    description: "Masonry tunnels, flooded channels, junctions, and chambers.",
    width: 36, height: 24, seed: "", scale: 7, mode: "sewer",
    waterWeight: 1, difficultWeight: .8, reliefWeight: 1,
    rockRatio: .01, treeRatio: 0, buildingCount: 0,
  },
  {
    id: "ancient-ruins", name: "Ancient ruins",
    description: "Collapsed halls, courtyards, broken roads, and overgrowth.",
    width: 36, height: 24, seed: "", scale: 8, mode: "ancient-ruins",
    waterWeight: .25, difficultWeight: 1.1, reliefWeight: .5,
    rockRatio: .045, treeRatio: .06, buildingCount: 7,
  },
  {
    id: "countryside",
    name: "Open countryside",
    description: "A main road, a pond, and open ground.",
    width: 36, height: 24, seed: "", scale: 10, mode: "countryside",
    waterWeight: 1, difficultWeight: 1, reliefWeight: 1,
    rockRatio: 0.02, treeRatio: 0.05, buildingCount: 2,
  },
  {
    id: "river",
    name: "River valley",
    description: "A continuous river, banks, a road, and a bridge.",
    width: 36, height: 24, seed: "", scale: 8, mode: "river",
    waterWeight: 1, difficultWeight: 1, reliefWeight: 1,
    rockRatio: 0.01, treeRatio: 0.09, buildingCount: 1,
  },
  {
    id: "coast",
    name: "Coastline",
    description: "An organic shoreline, beach, and coastal road.",
    width: 36, height: 24, seed: "", scale: 9, mode: "coast",
    waterWeight: 1, difficultWeight: 1, reliefWeight: 1,
    rockRatio: 0.03, treeRatio: 0.06, buildingCount: 1,
  },
  {
    id: "wetlands",
    name: "Wetlands",
    description: "Shallow pools, muddy ground, and winding channels.",
    width: 36, height: 24, seed: "", scale: 8, mode: "wetlands",
    waterWeight: 1, difficultWeight: 1, reliefWeight: 1,
    rockRatio: 0.005, treeRatio: 0.045, buildingCount: 0,
  },
  {
    id: "underground",
    name: "Underground",
    description: "Tight passages, rare chambers, rough ground, and underground pools.",
    width: 36, height: 24, seed: "", scale: 7, mode: "underground",
    waterWeight: 1, difficultWeight: 1, reliefWeight: 1,
    rockRatio: 0.02, treeRatio: 0, buildingCount: 0,
  },
  {
    id: "volcanic",
    name: "Volcanic wastes",
    description: "Lava lakes and flows, ash fields, and broken ridges.",
    width: 36, height: 24, seed: "", scale: 7, mode: "volcanic",
    waterWeight: 1, difficultWeight: 1, reliefWeight: 1,
    rockRatio: 0.07, treeRatio: 0, buildingCount: 0,
  },
  {
    id: "city",
    name: "City",
    description: "Connected streets, plazas, alleys, and dense urban blocks.",
    width: 36, height: 24, seed: "", scale: 8, mode: "city",
    waterWeight: 0, difficultWeight: 0.7, reliefWeight: 0,
    rockRatio: 0, treeRatio: 0.015, buildingCount: 8,
  },
  {
    id: "highlands",
    name: "Highlands",
    description: "Continuous ridges, a ravine, and a mountain pass.",
    width: 36, height: 24, seed: "", scale: 6, mode: "highlands",
    waterWeight: 1, difficultWeight: 1, reliefWeight: 1,
    rockRatio: 0.06, treeRatio: 0.03, buildingCount: 1,
  },
  {
    id: "house", name: "Generic house",
    description: "A living room with direct kitchen access, a hallway, and separate bedrooms.",
    width: 30, height: 22, seed: "", scale: 6, mode: "house",
    waterWeight: 0, difficultWeight: 0, reliefWeight: 0,
    rockRatio: 0, treeRatio: 0, buildingCount: 6,
  },
  {
    id: "spaceship", name: "Spaceship",
    description: "A central spine serving cockpit, engineering, crew, cargo, and specialist compartments.",
    width: 38, height: 22, seed: "", scale: 6, mode: "spaceship",
    waterWeight: 0, difficultWeight: 0, reliefWeight: 0,
    rockRatio: 0, treeRatio: 0, buildingCount: 9,
  },
  {
    id: "ship", name: "Sailing ship",
    description: "A central gangway serving the captain's cabin, galley, berths, and holds.",
    width: 42, height: 18, seed: "", scale: 6, mode: "ship",
    waterWeight: 0, difficultWeight: 0, reliefWeight: 0,
    rockRatio: 0, treeRatio: 0, buildingCount: 7,
  },
  {
    id: "castle", name: "Castle floor",
    description: "A great hall and defensive galleries connecting guardrooms, armory, kitchens, and private wings.",
    width: 36, height: 28, seed: "", scale: 6, mode: "castle",
    waterWeight: 0, difficultWeight: 0, reliefWeight: 0,
    rockRatio: 0, treeRatio: 0, buildingCount: 10,
  },
  {
    id: "cathedral", name: "Cathedral",
    description: "A massive cross-shaped nave with transepts, chapels, sacristy, and reliquary.",
    width: 30, height: 36, seed: "", scale: 6, mode: "cathedral",
    waterWeight: 0, difficultWeight: 0, reliefWeight: 0,
    rockRatio: 0, treeRatio: 0, buildingCount: 6,
  },
  {
    id: "tavern", name: "Tavern",
    description: "A large common room, connected kitchen, hallway, and private guest rooms.",
    width: 34, height: 24, seed: "", scale: 6, mode: "tavern",
    waterWeight: 0, difficultWeight: 0, reliefWeight: 0,
    rockRatio: 0, treeRatio: 0, buildingCount: 7,
  },
  {
    id: "crypt", name: "Crypt",
    description: "A processional passage with paired burial vaults and a deeper sanctum.",
    width: 34, height: 24, seed: "", scale: 6, mode: "crypt",
    waterWeight: 0, difficultWeight: 0, reliefWeight: 0,
    rockRatio: 0, treeRatio: 0, buildingCount: 9,
  },
];
