/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-configuration.d.ts` (hash: c7e6bb29e75b45161a43c7536a714f0a)
interface __BaseEnv_Env {
	GENERATED_MAP_RATE_LIMITER: RateLimit;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
