/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false worker/worker-configuration.d.ts` (hash: 8558b25f421680e7e1b0de7fe0b17ed8)
interface __BaseEnv_Env {
	MAP_IMAGES: R2Bucket;
	MAP_IMAGE_UPLOAD_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	MAP_STORAGE_COORDINATOR: DurableObjectNamespace<import("./index").MapStorageCoordinator>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "MapStorageCoordinator";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
